### ISSUE TITLE
Error when seeding dB

### ISSUE THREAD

**Issue by GLosch** [GLosch/rails-cookbook#1]
When running "rake db:seed", I get this error: 
NameError: uninitialized constant Recipe

The relevant table is called 'recipes', and in my seed file, here's an example of a new instance:
Recipe.create({
  f2f_url: "http://food2fork.com/view/46906",
  title: "Roast Chicken",
  recipe_id: "46906",
  image_url: "http://static.food2fork.com/roastchicken2feab.jpg",
  social_rank: 100
})  

User Story: https://trello.com/c/2aUeMQco/3-user-can-search-by-ingredients-on-hand
Steps taken: ensured the table name matches the "Recipe.create" syntax and compared to group project
Line causing error: https://github.com/GLosch/rails-cookbook/blob/master/db/seeds.rb#L9

**Comment by andrewfritz86** [comment]
Looks like you need to create a Recipe model in app/models. Rails is looking to create an instance of a Recipe class, but there is nothing in models.

**Comment by GLosch** [comment]
That did it, thanks!
