### ISSUE TITLE
API call returning error

### ISSUE THREAD

**Issue by GLosch** [GLosch/rails-cookbook#2]
When sending an ajax call to the food2fork api, this error appears in the console:
Uncaught SyntaxError: Unexpected token :

The actual data from the api call is showing up when I click on the error (http://prntscr.com/7d67li)
After clicking on the error: http://prntscr.com/7d67wy

But since the data doesn't show in the console, I can't make use of it in my app. 

Here's the source of the pain: https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/scratch.js#L10

I tried changing the url to google's homepage -- resulted in Uncaught SyntaxError: Unexpected token < (which was referring to the opening tag of the resulting data response, e.g. google's homepage)

I tried copying a full ajax call from a weather underground project, and that did work properly. 

I tried changing the dataType to regular json (vs. jsonp) and that throws a different error about 'Access-Control-Allow-Origin'

**Comment by andrewfritz86** [comment]
any different if you remove the datatype property from the request completely?

**Comment by GLosch** [comment]
Same error as when using "json" as the datatype (vs. jsonp):

XMLHttpRequest cannot load http://food2fork.com/api/search?key=089c1ff7f1ed08d8c9b2f763dd260fe4. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by andrewfritz86** [comment]
OK. I just hit it no problem with HTTParty and got a result, BUT it's possible that the API does not accept ajax requests (some apis don't). If that is the case, you can make a route in your server that you ajax, and that route triggers and api call, which your controller handles and then sends back to client.

**Comment by GLosch** [comment]
That could work, but when I change the URL to Google it still throws an error about a syntax issue

**Comment by andrewfritz86** [comment]
HRMMM

**Comment by andrewfritz86** [comment]
So-
1. make a route in routes.rb that fires a 'outside_call' method in any controller.
2. that method will make an extern http request with httparty.get. assign the response to a variable
3. send that variable back to the client with render json. that will be the data in the done function on the client side.

**Comment by andrewfritz86** [comment]
ALso, remember to capitalize HTTParty `HTTParty.get(url)`

**Comment by GLosch** [comment]
Getting alternating errors (timeout error and connection refused error) when trying to hit that new route: 

```Completed 500 Internal Server Error in 75170ms

Errno::ETIMEDOUT (Operation timed out - connect(2) for "food2fork.com" port 443):
  app/controllers/home_controller.rb:7:in `f2fcall'```

`Errno::ECONNREFUSED (Connection refused - connect(2) for "food2fork.com" port 443):
  app/controllers/home_controller.rb:7:in `f2fcall'`

https://github.com/GLosch/rails-cookbook/blob/master/config/routes.rb#L13
https://github.com/GLosch/rails-cookbook/blob/master/app/controllers/home_controller.rb#L6

**Comment by andrewfritz86** [comment]
Does it change if you take the s out of https in the request url from httparty?

**Comment by GLosch** [comment]
Returns this:
dateserverx-powered-byexpirespragmacache-controlset-cookievarycontent-lengthconnectioncontent-type

**Comment by andrewfritz86** [comment]
OK. The route is being hit, right? You can do a puts or binding.pry and hit said route? Put a inding.pry there, see if you can hit the API from pry.

**Comment by GLosch** [comment]
Yep, lets me access the "request" variable in pry, and shows returned data from the api call

**Comment by andrewfritz86** [comment]
I wonder if this will work. On my phone. Call dot class on response. It may
be a weird http arty object. If so try to call to_json on it and send the
result over.

**Comment by GLosch** [comment]
request.class returns: `HTTParty::Response`

I called .to_json on request and now it's giving me back correct data, so I think we're in the clear.
