### ISSUE TITLE
Backbone setup

### ISSUE THREAD

**Issue by GLosch** [GLosch/rails-cookbook#3]
Given the wireframes on the Trello board, here's what I'm thinking for Backbone:

Models: User, Recipe
Views: Recipe, RecipeCollection, Form
Collections: Recipes

**Comment by andrewfritz86** [comment]
Yeah looks good, and it won't be a problem to change this scheme later if you need to. I <3 backbone.

**Comment by GLosch** [comment]
Backbone and I are still in a tempestuous, early stage of our relationship. Sometimes I leave the toilet seat up just to annoy Backbone, and in turn, Backbone fills my shoes with nails.

**Comment by GLosch** [comment]
I'm trying to render the search form, but I'm stuck going back and forth between app.js and FormView.js.

When I instantiate the FormView in app.js (https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/backbone/app.js#L31), I need to pass it a model, but there is no model for this form, since it's static. Should the form not be a Backbone view then? Or does it need to have a corresponding model?

**Comment by andrewfritz86** [comment]
Best to pass the form a corresponding piece of the dom as an $el property upon instantiation

formView = new FormView({el: $("yourform")})

**Comment by GLosch** [comment]
Trying that, but the `render()` function won't trigger. I put in a log statement which isn't appearing in the console.

https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/backbone/app.js#L32
(should trigger this:)
https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/backbone/app.js#L32

**Comment by andrewfritz86** [comment]
OK. What is supposed to actually trigger the render function?

**Comment by GLosch** [comment]
Clicking this button: https://github.com/GLosch/rails-cookbook/blob/master/app/views/home/index.html.erb#L37

**Comment by andrewfritz86** [comment]
Hmm. Ok. looks like you are passing in the search form as the el that the view is watching, but the button that you want to hit is within the container div

**Comment by GLosch** [comment]
There are a couple of issues here:

-I have a 'search' route in app.js, which currently can't be triggered because there's no search route in routes.rb. I'm not sure I need that route at all. I added it for the purpose of triggering the search form, but it seems like it's unnecessary.

-Does the `#get-started` button have to be located elsewhere -- or be part of a Backbone view -- in order to trigger the formView?

**Comment by andrewfritz86** [comment]
Having a route for search is probably not needed at this point. Remember
that the reason for client-side routing is generally just to fire call
backs based off a url (probably from a button click). You could also just
have a button on the dom, listen to that button with a view, then render
the search form when the button is clicked.

**Comment by GLosch** [comment]
I'm trying to do the latter, without success. I have this listener, but it's not getting triggered:
https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/backbone/views/FormView.js#L6

So something in app.js isn't instantiating the FormView. I tried moving this block
`var formView = new Cookbook.Views.FormView({
        el: $("#container")
      });
      formView.render();`
into the `initialize` function in app.js, but that also doesn't trigger anything

**Comment by GLosch** [comment]
I think I found (at least one of the) problem(s). The promise object in app.js is waiting to fetch the current user, and that `.fetch()` call looks to be failing, which means that the router is never initialized in the first place.

**Comment by GLosch** [comment]
Is it possible that I need to reorganize my file structure so that my index.html.erb file is triggered by the `users_controller#show` method, rather than by the `HomeController#index` method as it currently stands?

Right now, the root is trying to access the `currentUser` object upon initialization (and failing, preventing the router from starting), which in turn is hitting the `users_controller#show` method. That method has no logic, and no template/view, so it breaks. 

I'll try moving the views/home/index.html.erb file such that the `users_controller#show` method hits it.

**Comment by GLosch** [comment]
Taking the promise object out of app.js allows the button click to be recognized, but it's still looking for a users/show file or template, which doesn't exist, so it's breaking. When using debugger in the middle of the FormView.render function, I can get the template to append to the #container div, but outside of debugger, it doesn't work.

**Comment by GLosch** [comment]
The form is now rendering, but I may be straying from the Backbone structure within my render function
https://github.com/GLosch/rails-cookbook/blob/master/app/assets/javascripts/backbone/views/FormView.js#L15

and the homepage is still getting a 500 error when trying to hit the user route:
(Missing template users/show)

**Comment by GLosch** [comment]
Finally got the user/show route to do what it had to do -- provide the currentUser attribute to the global Cookbook object. 500 error is resolved. 

Had to move this block:
`session_user = User.find(current_user.id).to_json(:include => :recipes)`
`render json: session_user`

into the users_controller#show route. It had been in the index route, which is the route that renders the homepage.
